name: Auto Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 45.90.229.210
          username: u203096280
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd ~/domains/websmaba.site/public_html
            ./deploy.sh
